CREATE TABLE "EVT_LOG" 
   (	"ID" NUMBER(*,0), 
	"EVT_NAME" VARCHAR2(255 CHAR), 
	"USER_CREATED" VARCHAR2(255 CHAR) DEFAULT user, 
	"DATETIME_START" TIMESTAMP (6) DEFAULT systimestamp, 
	"DATETIME_END" TIMESTAMP (6), 
	"DURATION_SEC" NUMBER(20,6), 
	"TABLE_NAME" VARCHAR2(255 CHAR), 
	"ROW_COUNT" NUMBER(38,0), 
	"STATUS" VARCHAR2(10 CHAR), 
	"ERROR_MESSAGE" VARCHAR2(2000 CHAR), 
	"INFO_MESSAGE" VARCHAR2(500 CHAR), 
	"CLOB_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
);
